//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001CNetFram4MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_eventos
    {
        public int id { get; set; }
        public string evento { get; set; }
        public Nullable<long> anio { get; set; }
        public Nullable<int> idEstatus { get; set; }
    }
}
